### ISSUE TITLE
Adding a publiccode.yml file?

### ISSUE THREAD

**Issue by bzg** [betagouv/tell-me#191]
[publiccode.yml](https://github.com/publiccodeyml/publiccode.yml) presents itself as a "metadata standard for public software": it was developed by [Team Digitale](https://teamdigitale.governo.it/en/) from the italian administration and some French public sector open source projects start using this standard.

We (at the [Free Software unit of DINUM](https://communs.numerique.gouv.fr/)) deployed this [online publiccode editor](https://publiccode-editor.etalab.studio/) as a way to promote the adoption of this standard.

We believe it can help **promote generic open source tools developed by the administration** - correct me if I'm wrong but it looks like _tell-me_ is exactly this :)

Would you consider adding such a file at the root of your repository?

You can see examples [here](https://github.com/codegouvfr/react-dsfr/blob/main/publiccode.yml) and [there](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/main/publiccode.yml).

Let me know if you have any question, I'd be glad to answer - and in French on mattermost.incubateur.net where I'm bzg.

**Comment by ivangabriele** [comment]
Hi and thanks for the suggestion. I didn't even know this even existed! I need first to focus on finalizing a stable-enough release in order to publish the `v1.0.0` version but I'll integrate it for this first version and ask for your help if I'm not sure about how to write and test it.

**Comment by bzg** [comment]
Thanks a lot for your answer, there is absolutely no rush and let me know if I can help.

**Comment by bzg** [comment]
Hello, we are working on a new version of our "Awesome code.gouv.fr" list of recommended Free Software made/published by the administration.  I thought it'd be time to ping you again about this.  Are you still active on the project?  Is it used and funded?  Thanks!

**Comment by ivangabriele** [comment]
@bzg Hi! No this project has been abandoned. and will surely be replaced by something based on Grist which will be part of [La Suite Numérique](https://lasuite.numerique.gouv.fr).

I will archive it ^^.
